diga = input('Diga algo ai ')
print('O tipo primitivo desse valor é ', type(diga))
print('Relatorio de teste sobre o que você digitou:')
print('Numero: ', diga.isnumeric())
print('Letras: ', diga.isalpha())
print('Alfanumerico: ', diga.isalnum())
print('Tudo em maiusculo: ', diga.isupper())
print('Tudo em minusculo: ', diga.islower())
print('Só tem espaços: ', diga.isspace())
print('Tá capitalizado: ', diga.istitle())
print('Caracteres ASCII: ', diga.isascii())
print('Decimais: ', diga.isdecimal())
print('Digitos: ', diga.isdigit())
print('Identificador: ', diga.isidentifier()) #regras de uma variavel js
print('Printavel: ', diga.isprintable())
